---
- hosts: localhost
  gather_facts: yes
  pre_tasks:
    - include_vars: 'main'
    - include_vars: 'vault'
  tasks:
    - name: Create ~/.ssh directory
      file:
        state: directory
        path: ~/.ssh
    - name: Create /usr/local/src directory
      file:
        state: directory
        path: /usr/local/src
        owner: '{{ ansible_user_uid }}'
        group: wheel
      become: yes
    - name: Create private key
      openssl_privatekey:
        state: present
        type: RSA
        size: 4096
        path: ~/.ssh/id_rsa
    - name: Create public key
      openssl_publickey:
        state: present
        privatekey_path: ~/.ssh/id_rsa
        path: ~/.ssh/id_rsa.pub
        format: OpenSSH
    - name: Read public key from file
      shell: cat ~/.ssh/id_rsa.pub
      register: public_key
    - name: Add public key to GitHub
      github_key:
        name: '{{ ansible_hostname }}'
        state: present
        pubkey: '{{ public_key.stdout }}'
        token: '{{ vault_github_token }}'
      when: vault_github_token is defined
- hosts: localhost
  tasks:
    - name: Install Homebrew taps
      homebrew_tap:
        name: '{{ item.name }}'
        url: '{{ item.url }}'
        state: present
      with_items: '{{ homebrew_taps }}'
    - name: Install Homebrew packages
      homebrew:
        name: '{{ item }}'
        state: present
      with_items: '{{ homebrew_packages }}'
    - name: Install Homebrew cask packages
      homebrew_cask:
        name: '{{ item }}'
        state: present
      with_items: '{{ homebrew_cask_packages }}'
    - name: Clone dotfiles repository
      git:
        repo: '{{ dotfiles_repo }}'
        dest: '/usr/local/src/dotfiles'
    - name: Install dotfiles
      make:
        chdir: '/usr/local/src/dotfiles'
        target: install
